
blank_issues_enabled: true
contact_links:
  - name: 운영 및 소식 작성 가이드라인
    url: https://oss.navercorp.com/fe-news/fe-news/wiki/%EC%9A%B4%EC%98%81-Guideline
    about: FE News 발행시 따라야 하는 가이드 라인
  - name: 일정별 담당자
    url: https://oss.navercorp.com/fe-news/fe-news/wiki/%EC%9D%BC%EC%A0%95%EB%B3%84-%EB%B0%9C%ED%96%89-%EB%8B%B4%EB%8B%B9%EC%9E%90
    about: 차기 소식 발행 담당자 확인